# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DEV LOG
email: seungwoo321@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  프론트엔드 개발자의 개발 일기. 프로젝트를 진행하며 겪은 시행착오와 기술 선택의 과정을 기록합니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://seungwoo321.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "Seungwoo321/seungwoo321.github.io"
# github_username:  Seungwoo321
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: air
paginate: 5
paginate_path: /page:num/
author:
  avatar: /assets/images/avata.png
  location: Seoul
  email: seungwoo321@gmail.com
  github: Seungwoo321
og_image: /assets/images/og.png
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# Analytics
# google_analytics: true
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : G-DLLRFBXZCW

# Google AdSense
adsense:
  ad_client: "ca-pub-7701657858733816"
  data_ad_format: "auto"
  data_full_width_responsive: "true"

encoding: "utf-8"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-multiple-languages-plugin
  - jekyll-seo-tag

# Multiple Languages
languages: ["ko", "en", "ja"]
default_lang: "ko"
default_lang_in_url: false
exclude_from_localizations: ["assets", "images", "css", "js"]

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
search                   : true # true, false (default) 블로그 내 검색창 활성화
search_full_content      : # true, false (default)
search_provider          : lunr # lunr (default), algolia, google

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      read_time: true
      show_date: true
      comments: true
      related: true
      excerpt_separator: <!--more-->
      sidebar:
        nav: "categories"